solve difference with bruno's errors?

diff --git a/test/all.diff b/test/all.diff
--- a/test/all.diff
+++ b/test/all.diff
@@ -1,40 +1,280 @@
-==> diffs/questionable_exec_dir.diff <==
+==> diffs/bonus_syntax_invalid4.diff <==
 diff of execution of:
-echo 'export PATH="$PATH:$PWD"; mkdir asdfg; asdfg' | tr ';' '\n' | [shell]
---- expected	2024-09-10 21:32:59.034768066 +0200
-+++ found	2024-09-10 21:32:59.086768424 +0200
-@@ -1,5 +1,6 @@
+echo '&& echo a' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:53.967686214 +0200
++++ found	2024-09-10 23:36:54.188683445 +0200
+@@ -1,5 +1,5 @@
  
  ======== stderr =======
-+[progname]: mkdir: command not found
- [progname]: asdfg: command not found
+-[syntax error msg]
++
  ======== return =======
  return value: 1
 
-==> diffs/questionable_glob_order.diff <==
+==> diffs/glob_both.diff <==
 diff of execution of:
-echo 'touch a b c A B C aa ab ac Aa Ab Ac aA aB aC; echo *' | tr ';' '\n' | [shell]
---- expected	2024-09-10 21:32:58.027761112 +0200
-+++ found	2024-09-10 21:32:58.107761665 +0200
+echo 'touch a.c b.c a.o b.o; echo *.*' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:55.141671506 +0200
++++ found	2024-09-10 23:36:55.231670379 +0200
 @@ -1,6 +1,6 @@
--a A aa aA Aa ab aB Ab ac aC Ac b B c C infile readonly
-+Ac a aC . aB infile aa .. readonly C A B Aa c ac ab aA b Ab
+-a.c a.o b.c b.o
++a.c . .. b.c b.o a.o
  
  ======== stderr =======
  
  ======== return =======
  return value: 0
 
-==> diffs/questionable_SHLVL.diff <==
+==> diffs/glob_cmd1.diff <==
 diff of execution of:
-echo 'echo $SHLVL' | tr ';' '\n' | [shell]
---- expected	2024-09-10 21:32:57.841759826 +0200
-+++ found	2024-09-10 21:32:57.928760428 +0200
-@@ -1,6 +1,6 @@
--2
-+3
+echo 'rm *; *' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:56.164658696 +0200
++++ found	2024-09-10 23:36:56.263657457 +0200
+@@ -1,5 +1,8 @@
+ 
+ ======== stderr =======
+-[progname]: *: command not found
++[progname]: cannot remove '.': Is a directory
++[progname]: cannot remove '..': Is a directory
++[progname]: .: filename argument required
++[progname]: usage: . filename [arguments]
+ ======== return =======
+ return value: 1
+
+==> diffs/glob_cmd2.diff <==
+diff of execution of:
+echo 'rm *; touch ls; *' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:56.389655880 +0200
++++ found	2024-09-10 23:36:56.491654603 +0200
+@@ -1,6 +1,8 @@
+-ls
+ 
+ ======== stderr =======
+-
++[progname]: cannot remove '.': Is a directory
++[progname]: cannot remove '..': Is a directory
++[progname]: .: filename argument required
++[progname]: usage: . filename [arguments]
+ ======== return =======
+-return value: 0
++return value: 1
+
+==> diffs/glob_empty.diff <==
+diff of execution of:
+echo 'mkdir empty; cd empty; echo *; echo .*' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:55.944661450 +0200
++++ found	2024-09-10 23:36:56.002660724 +0200
+@@ -1,7 +1,7 @@
+-*
++. ..
+ . ..
  
  ======== stderr =======
  
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_hidden2.diff <==
+diff of execution of:
+echo 'touch .hidden .test; echo .*; echo .hidd*' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:55.413668100 +0200
++++ found	2024-09-10 23:36:55.526666685 +0200
+@@ -1,7 +1,7 @@
+-. .. .hidden .test
++.test .hidden . ..
+ .hidden
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_in_var_quotes.diff <==
+diff of execution of:
+echo 'export a=\'"*file"\'; echo $a' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:57.054647557 +0200
++++ found	2024-09-10 23:36:57.136646531 +0200
+@@ -1,6 +1,6 @@
+-"*file"
++*file
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_mutli.diff <==
+diff of execution of:
+echo 'touch minini mini; echo *i*i*' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:55.587665921 +0200
++++ found	2024-09-10 23:36:55.713664343 +0200
+@@ -1,6 +1,6 @@
+-infile mini minini
++infile minini mini
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_mutliple.diff <==
+diff of execution of:
+echo 'echo * in* *' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:56.740651487 +0200
++++ found	2024-09-10 23:36:56.776651036 +0200
+@@ -1,6 +1,6 @@
+-infile readonly infile infile readonly
++. infile .. readonly infile . infile .. readonly
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_redir_ambiguous.diff <==
+diff of execution of:
+echo 'touch a b c; cat *;' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:57.231645343 +0200
++++ found	2024-09-10 23:36:57.287644643 +0200
+@@ -1,7 +1,8 @@
+ infile content
+ infile second line
+ 
+ ======== stderr =======
+-
++[progname]: .: Is a directory
++[progname]: ..: Is a directory
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_redir.diff <==
+diff of execution of:
+echo 'rm readonly; cat *;' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:56.572653590 +0200
++++ found	2024-09-10 23:36:56.661652476 +0200
+@@ -1,7 +1,8 @@
+ infile content
+ infile second line
+ 
+ ======== stderr =======
+-
++[progname]: .: Is a directory
++[progname]: ..: Is a directory
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_sdhfj.diff <==
+diff of execution of:
+echo 'touch bonus bonus_bonus; echo bo*s' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:58.008635622 +0200
++++ found	2024-09-10 23:36:58.171633584 +0200
+@@ -1,6 +1,6 @@
+-bonus bonus_bonus
++bonus_bonus bonus
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_simple.diff <==
+diff of execution of:
+echo 'echo *' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:54.440680288 +0200
++++ found	2024-09-10 23:36:54.492679637 +0200
+@@ -1,6 +1,6 @@
+-infile readonly
++. infile .. readonly
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/glob_sorted.diff <==
+diff of execution of:
+echo 'touch b c a; echo *' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:54.589678421 +0200
++++ found	2024-09-10 23:36:54.674677356 +0200
+@@ -1,6 +1,6 @@
+-a b c infile readonly
++a . infile .. readonly c b
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+ return value: 0
+
+==> diffs/or_pipe.diff <==
+diff of execution of:
+echo '(echo a && cat fail) || echo b | grep b' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:46.493780063 +0200
++++ found	2024-09-10 23:36:46.572779069 +0200
+@@ -1,7 +1,6 @@
+ a
+-b
+ 
+ ======== stderr =======
+-[progname]: fail: No such file or directory
++
+ ======== return =======
+ return value: 0
+
+==> diffs/parenthesis_redir_fail.diff <==
+diff of execution of:
+echo '(cat | grep a) < fail' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:53.071697445 +0200
++++ found	2024-09-10 23:36:53.215695640 +0200
+@@ -1,5 +1,5 @@
+ 
+ ======== stderr =======
+-[progname]: fail: No such file or directory
++
+ ======== return =======
+ return value: 1
+
+==> diffs/parenthesis_redir_in.diff <==
+diff of execution of:
+echo '(cat | grep in) < infile' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:52.432705459 +0200
++++ found	2024-09-10 23:36:52.472704957 +0200
+@@ -1,7 +1,5 @@
+-infile content
+-infile second line
+ 
+ ======== stderr =======
+ 
+ ======== return =======
+-return value: 0
++return value: 1
+
+==> diffs/parenthesis_redir_in_out.diff <==
+diff of execution of:
+echo '(cat | grep in) < infile > outfile; cat outfile' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:52.887699753 +0200
++++ found	2024-09-10 23:36:52.980698586 +0200
+@@ -1,7 +1,5 @@
+-infile content
+-infile second line
+ 
+ ======== stderr =======
+-
++[progname]: outfile: No such file or directory
+ ======== return =======
+-return value: 0
++return value: 1
+
+==> diffs/parenthesis_redir_out.diff <==
+diff of execution of:
+echo '(cat infile | grep in) > outfile; cat outfile' | tr ';' '\n' | [shell]
+--- expected	2024-09-10 23:36:52.647702763 +0200
++++ found	2024-09-10 23:36:52.750701470 +0200
+@@ -1,7 +1,7 @@
+ infile content
+ infile second line
+ 
+ ======== stderr =======
+-
++[progname]: outfile: No such file or directory
  ======== return =======
  return value: 0
